#Note: Can't just comment out token/secret/user_id when resetting--needs to be deleted
---
:oauth:
  :consumer_key: 537f25843e81488db9edf2f45c48e3d0
  :consumer_secret: 5db2d692a92c4a67bfa216de2be171ac
